# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Maxcraft\DefaultBundle\Entity\User:
          algorithm: sha1
          encode_as_base64: false
          iterations: 1
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
          users:
            entity: {class: MaxcraftDefaultBundle:User, property: username}
          in_memory:
            memory:
               users:
                   admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }


    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER, ROLE_MODO
            ROLE_MODO:        ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
            main:
                pattern: ^/
                anonymous: true
                provider: users
                form_login:
                  login_path: maxcraft_homepage
                  check_path: login_check
                logout:
                  path: logout
                  target: /

    access_control:
            #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
            #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
