<?php

namespace Maxcraft\DefaultBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository{

    public function findImages(Album $album){
        return $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:Image')->findBy(
            array('album'=> $album->getId()),
            array('id'=> 'desc'),
            null,
            0
        );
    }


    public function findAlbums(User $user, $private = false){

        if ($private){
            return $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:Album')->findBy(
                array('user' => $user->getId()),
                array('creationDate' => 'desc'),
                null,
                0
            );
        }
        else{
            return $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:Album')->findBy(
              array('user' => $user->getId(), 'display' => true),
              array('creationDate' => 'desc'),
              null,
              0
            );
        }
    }
}
