<?php

namespace Maxcraft\DefaultBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * BuilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuilderRepository extends EntityRepository
{
    public function findBuilderByZoneAndUser($zoneId, $userUuid){
        return $this->getEntityManager()->getRepository('MaxcraftdefaultBundle:Builder')->findBy(
            array('zone'=> $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:Zone')->find($zoneId),
                'user' => $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:User')->findByUuid($userUuid),
                'role'=>'BUILD'),
            null,
            null,
            0
        );
    }

    public function findCuboByZoneAndUser($zoneId, $userUuid){
        return $this->getEntityManager()->getRepository('MaxcraftdefaultBundle:Builder')->findBy(
            array('zone'=> $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:Zone')->find($zoneId),
                'user' => $this->getEntityManager()->getRepository('MaxcraftDefaultBundle:User')->findByUuid($userUuid),
                'role'=>'CUBO'),
            null,
            null,
            0
        );
    }
}
