<?php

namespace Maxcraft\DefaultBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findZones($user){

        $zones = $this->getEntityManager()->createQuery('SELECT z FROM MaxcraftDefaultBundle:Zone z WHERE z.owner = '.$user->getId());

        return $zones;
    }


}
