<?php

namespace Maxcraft\DefaultBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * WebZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebZoneRepository extends EntityRepository{


}
